# Generated by Django 2.2.1 on 2019-07-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('entry', models.CharField(max_length=255)),
                ('last_price', models.CharField(max_length=255)),
                ('buy_or_sell', models.CharField(max_length=255)),
                ('returns', models.CharField(max_length=255)),
                ('equity', models.CharField(max_length=255)),
            ],
        ),
    ]
