# Generated by Django 2.2.1 on 2019-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='last_price',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='returns',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
