# Generated by Django 2.2.1 on 2019-07-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlabs', '0002_auto_20190709_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
