# Generated by Django 2.2.1 on 2019-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlabs', '0003_auto_20190709_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('returns', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
