# Generated by Django 2.2.1 on 2019-07-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlabs', '0005_monthlylog_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='current_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
